const categoryImages = {
  "Animals": "/assets/images/Animals.jpg",
  "anime_manga": "/assets/images/anime_manga.jpg",
  "Art": "/assets/images/Art.jpg",
  "board_games": "/assets/images/board_games.jpg",
  "Books": "/assets/images/Books.jpg",
  "cartoon": "/assets/images/cartoon.jpg",
  "Celebrities": "/assets/images/Celebrities.jpg",
  "Comics": "/assets/images/Comics.jpg",
  "Computers": "/assets/images/Computers.jpg",
  "Film": "/assets/images/Film.jpg",
  "Gadgets": "/assets/images/Gadgets.jpg",
  "general_knowledge": "/assets/images/general_knowledge.jpg",
  "Geography": "/assets/images/Geography.jpg",
  "History": "/assets/images/History.jpg",
  "Mathematics": "/assets/images/Mathematics.jpg",
  "Music": "/assets/images/Music.jpg",
  "Musicals&Theatres": "/assets/images/Musicals&Theatres.jpg",
  "Mythology": "/assets/images/Mythology.jpg",
  "Politics": "/assets/images/Politics.jpg",
  "Science&Nature": "/assets/images/Science&Nature.jpg",
  "Sports": "/assets/images/Sports.jpg",
  "Television": "/assets/images/Television.jpg",
  "Vehicles": "/assets/images/Vehicles.jpg",
  "Video_Games": "/assets/images/Video_Games.jpg",
};

export default categoryImages;
