const categoryImages = {
  "Animals": "/assets/images/Animals.jpg",
  "Entertainment: Japanese Anime & Manga": "/assets/images/anime_manga.jpg",
  "Art": "/assets/images/Art.jpg",
  "Entertainment: Board Games": "/assets/images/board_games.jpg",
  "Entertainment: Books": "/assets/images/Books.jpg",
  "Entertainment: Cartoon & Animations": "/assets/images/cartoon.jpg",
  "Celebrities": "/assets/images/Celebrities.jpg",
  "Entertainment: Comics": "/assets/images/Comics.jpg",
  "Science: Computers": "/assets/images/Computers.jpg",
  "Entertainment: Film": "/assets/images/Film.jpg",
  "Science: Gadgets": "/assets/images/Gadgets.jpg",
  "General Knowledge": "/assets/images/general_knowledge.jpg",
  "Geography": "/assets/images/Geography.jpg",
  "History": "/assets/images/History.jpg",
  "Science: Mathematics": "/assets/images/Mathematics.jpg",
  "Entertainment: Music": "/assets/images/Music.jpg",
  "Entertainment: Musicals & Theatres": "/assets/images/Musicals&Theatres.jpg",
  "Mythology": "/assets/images/Mythology.jpg",
  "Politics": "/assets/images/Politics.jpg",
  "Science & Nature": "/assets/images/Science&Nature.jpg",
  "Sports": "/assets/images/Sports.jpg",
  "Entertainment: Television": "/assets/images/Television.jpg",
  "Vehicles": "/assets/images/Vehicles.jpg",
  "Entertainment: Video Games": "/assets/images/Video_Games.jpg",
};

export default categoryImages;
